export const DEFAULT_CATEGORIES = [
  {
    name: 'Gaji',
    type: 'income' as const,
    icon: 'CircleDollarSign',
    color: '#4CAF50',
  },
  {
    name: 'Freelance',
    type: 'income' as const,
    icon: 'BriefcaseBusiness',
    color: '#2196F3',
  },
  {
    name: 'Investasi',
    type: 'income' as const,
    icon: 'ChartLine',
    color: '#9C27B0',
  },
  {
    name: 'Hadiah',
    type: 'income' as const,
    icon: 'HandCoins',
    color: '#FF9800',
  },
  {
    name: 'Penjualan',
    type: 'income' as const,
    icon: 'Store',
    color: '#00BCD4',
  },
  {
    name: 'Lainnya',
    type: 'income' as const,
    icon: 'Wallet',
    color: '#607D8B',
  },
  {
    name: 'Makanan',
    type: 'expense' as const,
    icon: 'ShoppingBasket',
    color: '#F44336',
  },
  {
    name: 'Transportasi',
    type: 'expense' as const,
    icon: 'ArrowLeftRight',
    color: '#FF5722',
  },
  {
    name: 'Belanja',
    type: 'expense' as const,
    icon: 'ShoppingBag',
    color: '#E91E63',
  },
  {
    name: 'Hiburan',
    type: 'expense' as const,
    icon: 'Activity',
    color: '#673AB7',
  },
  {
    name: 'Kesehatan',
    type: 'expense' as const,
    icon: 'ShieldCheck',
    color: '#3F51B5',
  },
  {
    name: 'Pendidikan',
    type: 'expense' as const,
    icon: 'Briefcase',
    color: '#009688',
  },
  {
    name: 'Tagihan',
    type: 'expense' as const,
    icon: 'ReceiptText',
    color: '#795548',
  },
  {
    name: 'Lainnya',
    type: 'expense' as const,
    icon: 'Calculator',
    color: '#9E9E9E',
  },
  {
    name: 'Dana darurat',
    type: 'allocation' as const,
    icon: 'PiggyBank',
    color: '#388E3C',
  },
  {
    name: 'Tabungan tujuan',
    type: 'allocation' as const,
    icon: 'Vault',
    color: '#5C6BC0',
  },
  {
    name: 'Alokasi investasi',
    type: 'allocation' as const,
    icon: 'ChartPie',
    color: '#8E24AA',
  },
] as const;
